language: smalltalk
sudo: false

os:
  - linux

smalltalk:
  - Pharo-5.0
  - Pharo-6.0

env:
  global:
    - secure: K5Fo1GyFgwsE/JaUI7hD3cLjdsYmxJdLnF9ppUoxgpaz3z/nZ6RpxdrjhkotKxdPuyL1mpZSi/Ynzt0v7hmAoUcwUhbIwykrNt7IfI8x/pUiLX864T8W4d10U1QFKxr5+6E1rqHWpXYXO/jTyJUk2q2jvGIWbHMFWFvIQwbDnWgy38w0Yo+XfwMCgFUebmTJEZBJhYFeSqVKZt6twtXJk8/z40zwc3jQx9ClEhBHqao0O+Od4d3WWOukEvG3FxG/70KjX6WIH/1EwEtLcPHMwOeqObVxOqCAuSDHrW7BCTkil6Sv7b5m/R3I3Ly6X5uMLbditTThmvC7i+jKIz4wVyAmE90K2JnlfGWZ+fKyiFZQ7ei1rEBNjQ49mDoPUTci5ntuTiIi7RZyY3QO4svaFvdz1dLkdeydft0t/CaNBNahBp2lw1ObP/RycKdEWgd7NF5CoeEqTvzlBm8xgyN5/B0F3w1+v8lmNmkIenckb6AQJXk9Li9kFSJJjHVyvMuWzPKemk5MLFNBnNwB4wCwHdNsKY7PNLL7DXPEEwW/pUtOIpG37w10bktfY7hoVr179UBEglphdfTgqXS7GNinQ9h0e7l8M2xtQ+aYJmMiWfLphb0GQFGLYbH9Osy0ETyPO5m4j5mYvn1qJ8Mvt8lXYS9yo9xXQlP15itXeHOrWz0=
    - secure: gxmIrk9mR5xgV3bSDqQ7YsmvK7I1CA3bMj6TDXcEa29olg9knaYUIBQCdUFD3coG72yRBXs/lHsyUIuVVf62bprOjWTeK2F3B/FI+beJH0mQI+mTqj+fnhkkFj8msdYSJaSfvf/7K9B7JBzGafCNGB6HXucKivD2pwxM65bG9hSHbTMscpWR4IyHoJ6G74+ha+aRhOlqGgz096mTATfGisdmjImv+8vMWUohCnorjJ+Wgq3W5KU5pHq8QqAZHlF+dy1qVfHvkw688D08O71BOJyzFMoL7f3WIXtG5K5Csb1k11ZUQ/CjIRzir3UrgjPe4sjqW1zGEqVTKDTPP07HwMAmTQgrSo6Ct28oMGQeH3CsOTOvlCHIsokXepPWHLyJWC1urKe+21CRINalH48tBOYkNVx6oP7gFidBRhamymTL7SxWCGNg2vzfMrTmKtKIIn1bj5t1tXocdnIYieyo/mD/zaG7BQGgbpWgoFDT4FtIk5glb+gncCBNLk092Bz4y6cpoJ8+00W3G5plhfl714WiyU2C5ZlAiPyltdm8B+OLjGw8NU/NAnqc4+8iJE0XDvVlkP3WcRbCJ1tVKSJS5+HIZpp/p+QrYlTfrhuAWRVrA/qSoDXXa1pfZeUU4XBEus6/2UD8AXNYWioZ8Y+iJrLD8wSBqq3Fr8qWBiG6IU8=