language: smalltalk
sudo: false

os:
  - linux

smalltalk:
  - Pharo-5.0
  - Pharo-6.0

after_success:
  - ./scripts/run-coverage.sh

deploy:
  provider: s3
  access_key_id:
    secure: arZyyxOl33azm0Sm66eyzpzBLH7UccBdc87816bcKn0kxb93D8pmYC8uerSP47SnV2NM/Y+qzWJDuNLq4HgFGuDDgvawtbkhxrjQQj1Z/VGT74klteH1g/T7704ttYEk2rGReNDVvFyNTUtwQ98fLOsn2TL48amMCN77BrgYGkMofWiZ1Kt1NV8D9cIcOj6OuVscmfA2fw/o+Z8i6cDuqPSLKXkTWFEgB9mQZtt+AQOE9iQpiOd/aw2Zcu0WaXSFhKsgTDYOWC+40bP27UAfWYWGYrXR456ceMraMMbCOZNBIvbpgN9B52kRgPAgzwgpFK/o/rukiwhjpVlp0N1sUGtFZeVnmWOPLN09SBcSZswgfo1bSn0qfT/OfK0CnzcdVVn4uFn4gUll7Q8ol+VpMYI/jqgkhrR52wi6EcsukJ1xtVsn6IEa/2F206kwYFpMS8wWlBTktSsVP88roVaI1YBgpEbAXhnnfguZbnLH0E2QA7vFQRIsOOLeZJLW3mSPJ7K8QjsSW6e3tYu7dUs+CTGo2AOgwjT1zN++3gafEyEDpyHgBu+7Dy+CeGgg3yG9a8RNXnezSW4UKLBnQQ0KD3X05gWJ6Qjw/lA9I9ySYS2vdtURgpdpKIR+KiornEzuNd8KAaYM6izgc3V2T6LraMbZ4wknAdTgCvIVmzVdtP8=
  secret_access_key:
    secure: SvoBSzkL0vmAEFLDRw0wYTAaZtWUJkaw6NZ0lQg5aYhhTiW9E+iP2NGl/NUM2hLdHEG5yAcdUqymBIVOM0TpUrbHAqyY/zlVqEnOFL2Rjr7NwU2QLJ1YC/im9q6hogBc4TwWMtpKTA6Vdtk11n6DRNdE8FXWuwkqO3EBuJ7UMoBR2FFt4pB08FRs/NEuD58OSWx8plEIXJIQf2bMXMyhVJJTUwuMxdiBr6L5qgOJZHeDcRNYQmpk15xnh9/tdlhlkSCHG7GB2/hd3CU+pXa7fzwTGsfj+dMCovPS7D6awvG5k2sEFNwpkT9K+y0ohmu06HtfhCiaJ46Y50BNPmIFKBrpCnY0ECRL6F7SKxDJe5N/aG7KVmxQ3VIkRYMN8R1pOTNtMHZ8i3Y3PX075mMDHyZipAGkEM48pg7TA+/vCBBDwRis2bDXXOb7Lt8Xuk/psGBO3VakZ/XtQrjmBeqvSgd5NeoPe2ZCgeV9daSrHidlBeYztRZNYcBks5Kg5orPXJ64BG8nT3wJKChGRLpXfLpJPjuN1IWBLzili2LErFF2uLzugG9NOZoUan33qDIWUskmOYkkhzxbzqcLcrxv4njrPqcnF4l07VsMm5ddo18wutcCLS5LFOsg0cWJ78Mij5oHU3nIAtyswcTUFrS+XntaxjNAyFrGPN/jwux9EqA=
  bucket: "gh-coverage.peteruhnak.com"
  region: eu-central-1
  local_dir: coverage-result
  upload-dir: uml-shapes/$TRAVIS_BUILD_NUMBER/
  on:
    branch: s3